[package]
name = "spider"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19"
url = "=2.2.2"
reqwest = { version = "=0.11.22", default-features = false, features = ["blocking", "rustls-tls"] }
scraper = "0.18"